Repository IgniteUI/igniteui-angular-i18n, pull requests merged in 2019-05, with the labels that each got.

#16 Created Spanish resource strings for time-picker
  src/i18n/ES/time-picker-resources.ts
Labels: status: verified

#13 Update resource strings for Excel Style filtering
  package-lock.json
  package.json
  src/i18n/JA/grid-resources.ts
  src/i18n/KO/grid-resources.ts
Labels: status: localized, status: verified

#14 Created spanish Resources
  src/i18n/ES/grid-resources.ts
  src/i18n/ES/resources.ts
Labels: i18n, status: localized
