Repository IgniteUI/igniteui-angular-i18n, pull requests merged in 2021-05, with the labels that each got.

#70 [12.0.x] Fixing localization to match UI behaviour
  src/i18n/DE/grid-resources.ts
  src/i18n/ES/grid-resources.ts
  src/i18n/FR/grid-resources.ts
  src/i18n/IT/grid-resources.ts
  src/i18n/JA/grid-resources.ts
  src/i18n/KO/grid-resources.ts
  src/i18n/ZH-HANS/grid-resources.ts
  src/i18n/ZH-HANT/grid-resources.ts
Labels: status: awaiting-test

#69 [11.1.x] Localization fixes to match UI behaviour.
  src/i18n/DE/grid-resources.ts
  src/i18n/ES/grid-resources.ts
  src/i18n/FR/grid-resources.ts
  src/i18n/IT/grid-resources.ts
  src/i18n/JA/grid-resources.ts
  src/i18n/KO/grid-resources.ts
  src/i18n/ZH-HANS/grid-resources.ts
  src/i18n/ZH-HANT/grid-resources.ts
Labels: status: awaiting-test

#73 [ES] Updating localization - 10.2.x
  src/i18n/ES/carousel-resources.ts
  src/i18n/ES/date-range-picker-resources.ts
  src/i18n/ES/grid-resources.ts
  src/i18n/ES/list-resources.ts
  src/i18n/ES/paginator-resources.ts
Labels: status: verified

#74 [ES] Updating localization - 11.1.x
  src/i18n/ES/calendar-resources.ts
  src/i18n/ES/carousel-resources.ts
  src/i18n/ES/date-range-picker-resources.ts
  src/i18n/ES/grid-resources.ts
  src/i18n/ES/list-resources.ts
  src/i18n/ES/paginator-resources.ts
Labels: status: verified

#75 [ES] Updating localization - 12.0.x
  src/i18n/ES/calendar-resources.ts
  src/i18n/ES/carousel-resources.ts
  src/i18n/ES/date-range-picker-resources.ts
  src/i18n/ES/grid-resources.ts
  src/i18n/ES/list-resources.ts
  src/i18n/ES/paginator-resources.ts
Labels: status: verified

#72 BG localization 10.2.x
  src/i18n/BG/carousel-resources.ts
  src/i18n/BG/date-range-picker-resources.ts
  src/i18n/BG/grid-resources.ts
  src/i18n/BG/list-resources.ts
  src/i18n/BG/paginator-resources.ts
  src/i18n/BG/resources.ts
  src/i18n/BG/time-picker-resources.ts
  src/index.ts
Labels: i18n: Bulgarian, status: verified

#71 BG localization 11.1.x
  src/i18n/BG/calendar-resources.ts
  src/i18n/BG/carousel-resources.ts
  src/i18n/BG/date-range-picker-resources.ts
  src/i18n/BG/grid-resources.ts
  src/i18n/BG/list-resources.ts
  src/i18n/BG/paginator-resources.ts
  src/i18n/BG/resources.ts
  src/i18n/BG/time-picker-resources.ts
  src/index.ts
Labels: i18n: Bulgarian, status: verified

#77 BG localization - 12.0.x
  src/i18n/BG/calendar-resources.ts
  src/i18n/BG/carousel-resources.ts
  src/i18n/BG/date-picker-resources.ts
  src/i18n/BG/date-range-picker-resources.ts
  src/i18n/BG/grid-resources.ts
  src/i18n/BG/list-resources.ts
  src/i18n/BG/paginator-resources.ts
  src/i18n/BG/resources.ts
  src/i18n/BG/time-picker-resources.ts
  src/i18n/BG/tree-resources.ts
  src/index.ts
Labels: i18n: Bulgarian, status: verified

#68 BG localization- master
  src/i18n/BG/calendar-resources.ts
  src/i18n/BG/carousel-resources.ts
  src/i18n/BG/date-picker-resources.ts
  src/i18n/BG/date-range-picker-resources.ts
  src/i18n/BG/grid-resources.ts
  src/i18n/BG/list-resources.ts
  src/i18n/BG/paginator-resources.ts
  src/i18n/BG/resources.ts
  src/i18n/BG/time-picker-resources.ts
  src/i18n/BG/tree-resources.ts
  src/index.ts
Labels: i18n: Bulgarian, status: verified

#79 Cleanup grid resources - 10.2.x
  package-lock.json
  package.json
  src/i18n/BG/grid-resources.ts
  src/i18n/ES/grid-resources.ts
  src/i18n/IT/grid-resources.ts
  src/i18n/JA/grid-resources.ts
  src/i18n/KO/grid-resources.ts
  src/i18n/ZH-HANS/grid-resources.ts
  src/i18n/ZH-HANT/grid-resources.ts
Labels: bug, status: verified, version: 10.2.x
